[package]
name = "wordle"
version = "0.1.0"
edition = "2021"
readme = "README.md"
repository = "https://github.com/DoctorDalek1963/wordle"
license = "MIT"

[workspace]
members = ["cli", "web"]

[dependencies]
rand = "0.8.5"
thiserror = "1.0.35"
