[watch]
ignore = ["sass.css", "sass.css.map", "_main.css"]

[[hooks]]
stage = "pre_build"
command = "sass"
command_arguments = ["main.scss", "sass.css"]

[[hooks]]
stage = "pre_build"
command = "postcss"
command_arguments = ["--use", "autoprefixer", "-o", "_main.css", "sass.css"]
